export const HERE_MAP_STYLES = {
  editorVersion: '1.2.1',
  base: { style: 'oslo', scheme: 'normal.day' },
  definitions: {
    'WaterPark.Color': ['interpolate', ['linear'], ['zoom'], 0, '#CACED280', 9, '#CACED259'],
    'WaterPark.Label.Color': '#707A7F',
    'WaterPark.Label.Outline.Color': '#DCDFE299',
    'NationalPark.SecondOutline.Color': ['interpolate', ['linear'], ['zoom'], 10, '#D0D3D724', 15, '#C4C9CD24'],
    'WaterPark.Outline.Color': ['interpolate', ['linear'], ['zoom'], 7, '#A0A7AC4D', 16, '#A2A9AE4D'],
    'WaterPark.SecondOutline.Color': ['interpolate', ['linear'], ['zoom'], 10, '#B6BBC024', 16, '#A9AFB424'],
    'NativeReservation.SecondOutline.Color': ['interpolate', ['linear'], ['zoom'], 10, '#C0C4C824', 15, '#BFC3C724'],
    'MilitaryBase.SecondOutline.Color': ['interpolate', ['linear'], ['zoom'], 10, '#C1C6CA24', 15, '#BEC2C724'],
    'LandParcelBoundary.Color': '#B9BEC264',
    'CityCenter.Class6.Label.Color': '#2D3133',
    'CityCenter.Class6.Label.Outline.Color': '#E8EAEDB5',
    'CityCenter.Class7.Label.Color': '#313638',
    'CityCenter.Class7.Label.Outline.Color': '#E8EAEDB5',
    'POI.Accomodation.Label.Color': '#626A6F',
    'POI.Automotive.Label.Color': '#5283ED',
    'POI.BusinessServicesAreas.Label.Color': '#5283ED',
    'POI.EatDrink.Label.Color': '#C87329',
    'POI.Emergency.Label.Color': '#C84031',
    'POI.Entertainment.Label.Color': '#3C7E40',
    'POI.Facilities.Label.Color': '#596D79',
    'POI.LeisureOutdoor.Label.Color': '#3C7E40',
    'POI.Shopping.Label.Color': '#5283ED',
    'POI.SightsMuseum.Label.Color': '#3B838F',
    'POI.TransitStop.Label.Color': '#5B6468',
    'Rail.SecondLine.Color': '#A3AAAF',
    'Chairlift.Outline.Color': '#43494C00',
    'SkiRun.Arrow.Color': ['interpolate', ['linear'], ['zoom'], 17, '#C3C8CC00', 18, '#C3C8CC'],
    'Beach.Color': ['interpolate', ['linear'], ['zoom'], 9, '#DADDE0', 11, '#DBDEE1', 13, '#DCDFE1'],
    'Beach.Label.Color': '#60686D',
    'Beach.Label.Outline.Color': '#E4E6EA99',
    'Building.Color': '#F1F3F4',
    'Building.Outline.Color': '#B3B4B7',
    'Building.Label.Color': '#3B838F',
    'Building.Label.Outline.Color': '#FFFFFF',
    'BuildingAddress.Label.Color': '#515458',
    'BuildingAddress.Label.Outline.Color': '#E8EAEDBF',
    'BuiltupArea.Color': ['interpolate', ['linear'], ['zoom'], 14.3, '#E8EAED', 18.8, '#F8F9FA'],
    'Neighborhood.Label.Color': '#000000',
    'Neighborhood.Label.Outline.Color': '#E8EAEDB5',
    'CityCenter.Class1.Label.Outline.Color': '#E8EAEDB5',
    'CityCenter.Class2.Label.Color': '#090A0A',
    'CityCenter.Class2.Label.Outline.Color': '#E8EAEDB5',
    'CityCenter.Class3.Label.Color': '#121314',
    'CityCenter.Class3.Label.Outline.Color': '#E8EAEDB5',
    'CityCenter.Class4.Label.Color': '#1A1D1E',
    'CityCenter.Class4.Label.Outline.Color': '#E8EAEDB5',
    'CityCenter.Class5.Label.Color': '#232628',
    'CityCenter.Class5.Label.Outline.Color': '#E8EAEDB5',
    'CityCenter.Hamlet.Label.Color': '#2C3032',
    'CityCenter.Hamlet.Label.Outline.Color': '#E8EAEDB5',
    'Continent.Label.Color': '#484E52CC',
    'Continent.Label.Outline.Color': '#E6E8EA99',
    'CountryBoundary.Color': '#D4D5D5',
    'CountryBoundary.Outline.Color': '#6F869100',
    'StateBoundary.Color': '#606368',
    'StateBoundary.Width': 0,
    'StateBoundary.Outline.Color': '#C2C7CB1A',
    'CountryBoundary.Disputed.Color': [
      'interpolate',
      ['linear'],
      ['zoom'],
      0,
      '#C9CDD1',
      4,
      '#A0A6AB',
      6,
      '#828B91',
      11,
      '#828B91',
      13,
      '#7D868C',
    ],
    'CountryBoundary.Disputed.Outline.Color': [
      'interpolate',
      ['linear'],
      ['zoom'],
      0,
      '#ADB3B700',
      4,
      '#ADB3B720',
      12,
      '#949CA11A',
    ],
    'StateBoundary.Disputed.Color': ['interpolate', ['linear'], ['zoom'], 6, '#C6CACE', 11, '#AAB0B5', 16, '#A6ADB1'],
    'StateBoundary.Disputed.Outline.Color': '#C2C7CB1A',
    'Country.Label.Color': '#000000',
    'Country.Label.Outline.Color': '#FFFFFF',
    'State.Label.Color': '#000000',
    'State.Label.Outline.Color': '#FFFFFF',
    'Ferry.Line.Color': '#D9DCDF',
    'Ferry.Label.Color': '#E8EAED',
    'Ferry.Label.Outline.Color': '#A4ABAF',
    'Desert.Color': '#F0E9D9',
    'Desert.Label.Color': '#899197',
    'Desert.Label.Outline.Color': '#E2E5E899',
    'Glacier.Color': ['interpolate', ['linear'], ['zoom'], 10, '#DFE1E4', 16, '#DCDFE2'],
    'Glacier.Label.Color': '#555D61',
    'Glacier.Label.Outline.Color': '#DDDFE399',
    'IndustrialComplex.Color': ['interpolate', ['linear'], ['zoom'], 15, '#D8DBDE', 16, '#D8DBDE'],
    'IndustrialComplex.Label.Color': '#646D72',
    'IndustrialComplex.Label.Outline.Color': '#DDDFE399',
    'Airport.Color': ['interpolate', ['linear'], ['zoom'], 9, '#D4D8DB', 13, '#D9DCDF'],
    'Cemetery.Color': '#D8DBDE',
    'Allotment.Color': '#D8DBDE',
    'HarborArea.Color': ['interpolate', ['linear'], ['zoom'], 15, '#D8DBDE', 16, '#D8DBDE'],
    'HospitalCampus.Color': '#F9E9E6',
    'PedestrianArea.Color': ['interpolate', ['linear'], ['zoom'], 15, '#D8DBDE', 16, '#D8DBDE'],
    'Railyard.Color': ['interpolate', ['linear'], ['zoom'], 15, '#D8DBDE', 16, '#D8DBDE'],
    'ShoppingComplex.Color': '#FEFBF1',
    'SportsComplex.Color': '#B2D9B8',
    'UniversityCampus.Color': '#DCDFE2',
    'Park.Color': '#B2D9B8',
    'Park.Label.Color': '#3C7E40',
    'Park.Label.Outline.Color': '#FFFFFF',
    'AmusementPark.Color': '#D8DBDE',
    'AnimalPark.Color': '#D8DBDE',
    'GolfCourse.Color': '#B2D9B8',
    'Island.Label.Color': '#000000',
    'Island.Label.Outline.Color': '#DFE1E446',
    'POI.MountainPeak.Label.Color': '#3C7E40',
    'POI.MountainPeak.Label.Outline.Color': '#E6E8EB99',
    'MilitaryBase.Color': ['interpolate', ['linear'], ['zoom'], 7, '#D2D6D94B', 13, '#D2D6D941', 16, '#D2D6D928'],
    'MilitaryBase.Outline.Color': ['interpolate', ['linear'], ['zoom'], 7, '#C2C7CB4D', 15, '#BFC3C74D'],
    'MilitaryBase.Label.Color': '#656E73',
    'MilitaryBase.Label.Outline.Color': '#E0E3E699',
    'NationalPark.Color': '#EADDC4',
    'NationalPark.Outline.Color': ['interpolate', ['linear'], ['zoom'], 7, '#BFC3C74D', 15, '#BCC1C54D'],
    'NationalPark.Label.Color': '#6F797E',
    'NationalPark.Label.Outline.Color': '#E0E2E599',
    'NativeReservation.Color': ['interpolate', ['linear'], ['zoom'], 7, '#D5D8DC4B', 13, '#D5D8DC3C', 16, '#D6D9DD28'],
    'NativeReservation.Outline.Color': ['interpolate', ['linear'], ['zoom'], 7, '#C8CCD04D', 15, '#C1C6CA4D'],
    'NativeReservation.Label.Color': '#6C767B',
    'NativeReservation.Label.Outline.Color': '#DEE0E499',
    'Rail.Line.Color': '#C0C5C9',
    'Runway.Color': ['interpolate', ['linear'], ['zoom'], 11, '#CED1D5', 14, '#D1D5D8'],
    'Lake.Label.Color': '#2C59B6',
    'Lake.Label.Outline.Color': '#FFFFFF',
    'River.Label.Color': '#000000',
    'River.Label.Outline.Color': '#FFFFFF',
    'CanalWaterChannel.Label.Color': '#5F676C',
    'CanalWaterChannel.Label.Outline.Color': '#DDDFE34B',
    'IntermittentRiver.Label.Color': '#5F676C',
    'IntermittentRiver.Label.Outline.Color': '#DDDFE34B',
    'Street.Category0.Ramp.Width': [
      'interpolate',
      ['linear'],
      ['zoom'],
      13,
      3,
      14,
      7.2,
      15,
      11.1,
      16,
      15,
      17,
      18.6,
      18,
      32.4,
      20,
      64.8,
      24,
      455.4,
    ],
    'Street.Category0.Bridge.Color': '#6E787D3C',
    'Street.Category0.Arrow.Color': [
      'interpolate',
      ['linear'],
      ['zoom'],
      16.75,
      '#949CA100',
      17,
      '#949CA1',
      20,
      '#949CA1',
      24,
      '#A2A9AE',
    ],
    'Street.Category0.Label.Color': '#C84031',
    'Street.Category0.Label.Outline.Color': '#FFFFFF',
    'Street.Category1.Label.Color': '#000000',
    'Street.Category1.Label.Outline.Color': [
      'interpolate',
      ['linear'],
      ['zoom'],
      11,
      '#E8EAEDF2',
      12,
      '#E8EAEDF2',
      14,
      '#E8EAEDD9',
      17,
      '#E8EAEDCC',
    ],
    'Street.Category1.Label.Ramp.Size': 0,
    'Street.Category2.Label.Color': '#C84031',
    'Street.Category2.Label.Outline.Color': '#FFFFFF',
    'Street.Category2.Label.Ramp.Size': 0,
    'Street.Category3.Label.Color': '#000000',
    'Street.Category3.Label.Outline.Color': '#FFFFFF',
    'Street.Category3.Label.Ramp.Size': 0,
    'Street.Category4.Label.Color': '#3C3834',
    'Street.Category4.Label.Outline.Color': [
      'interpolate',
      ['linear'],
      ['zoom'],
      11,
      '#E8EAEDF2',
      12,
      '#E8EAEDF2',
      14,
      '#E8EAEDD9',
      17,
      '#E8EAEDCC',
    ],
    'Street.Pedestrian.Label.Color': '#000000',
    'Street.Pedestrian.Label.Outline.Color': '#E8EAED96',
    'Street.Walkway.Label.Color': '#000000',
    'Street.Walkway.Label.Outline.Color': '#E0E3E6A6',
    'Street.Category4.Width': [
      'interpolate',
      ['linear'],
      ['zoom'],
      11.5,
      2,
      13.2,
      1,
      13.9,
      0,
      16.1,
      2,
      16.5,
      9,
      19.6,
      9,
    ],
    'Street.Category0.Centerline.Width': 1,
    'Street.Category0.Outline.Color': '#D69131',
    'Street.Category0.Centerline.Color': '#F9E39D',
    'Street.Category1.Outline.Color': '#EEB441',
    'Street.Category2.Outline.Color': '#B8B6B6',
    'Street.Category3.Outline.Color': '#B8B6B6',
    'Street.Category4.Outline.Color': '#DADCE0',
    'Street.Pedestrian.Outline.Color': '#000000',
    'Street.Walkway.Outline.Color': '#000000',
    'CongestionZone.Outline.Color': '#323739',
    'EnvironmentalZone.Color': [
      'interpolate',
      ['linear'],
      ['zoom'],
      0,
      '#69727733',
      9,
      '#69727726',
      10,
      '#69727726',
      11,
      '#69727721',
      12,
      '#6972771A',
      13,
      '#6972770D',
      20,
      '#69727703',
    ],
    'EnvironmentalZone.Outline.Color': '#697277',
    'CongestionZone.Label.Color': '#323739',
    'CongestionZone.Label.Outline.Color': '#D0D3D780',
    'EnvironmentalZone.Label.Color': '#697277',
    'EnvironmentalZone.Label.Outline.Color': '#D9DCDF80',
    'Water.0m.Color': '#93B3F3',
    'Woodland.Label.Color': '#636C71',
    'Woodland.Label.Outline.Color': '#DFE1E466',
    'Land.Color': ['interpolate', ['linear'], ['zoom'], 11.5, '#C2E0C3'],
    'Woodland.Color': '#A1D0A8',
    'Airport.Label.Color': '#5F676C',
    'Airport.Label.Outline.Color': '#DCDFE299',
    'Cemetery.Label.Color': '#677075',
    'Cemetery.Label.Outline.Color': '#DFE1E499',
    'Allotment.Label.Color': '#677075',
    'Allotment.Label.Outline.Color': '#DFE1E499',
    'HarborArea.Label.Color': '#646D72',
    'HarborArea.Label.Outline.Color': '#DDDFE399',
    'HospitalCampus.Label.Color': '#C84031',
    'HospitalCampus.Label.Outline.Color': '#FFFFFF',
    'PedestrianArea.Label.Color': '#646D72',
    'PedestrianArea.Label.Outline.Color': '#DDDFE399',
    'Railyard.Label.Color': '#646D72',
    'Railyard.Label.Outline.Color': '#DDDFE399',
    'ShoppingComplex.Label.Color': '#646D72',
    'ShoppingComplex.Label.Outline.Color': '#DDDFE399',
    'SportsComplex.Label.Color': '#3C7E40',
    'SportsComplex.Label.Outline.Color': '#FFFFFF',
    'UniversityCampus.Label.Color': '#697277',
    'UniversityCampus.Label.Outline.Color': '#DDDFE399',
    'AmusementPark.Label.Color': '#677075',
    'AmusementPark.Label.Outline.Color': '#DFE1E499',
    'AnimalPark.Label.Color': '#677075',
    'AnimalPark.Label.Outline.Color': '#DFE1E499',
    'GolfCourse.Label.Color': '#3C7E40',
    'GolfCourse.Label.Outline.Color': '#DBDEE199',
    'Street.Category1.Bridge.Color': '#6E787D3C',
    'Street.Category1.Arrow.Color': [
      'interpolate',
      ['linear'],
      ['zoom'],
      16.75,
      '#9FA5AA00',
      17,
      '#A0A6AB',
      20,
      '#A0A6AB',
      24,
      '#ABB1B5',
    ],
    'Street.Category2.Bridge.Color': '#6E787D3C',
    'Street.Category2.Arrow.Color': [
      'interpolate',
      ['linear'],
      ['zoom'],
      17,
      '#AEB4B800',
      17.25,
      '#AEB4B8',
      20,
      '#AEB4B8',
      24,
      '#B9BEC2',
    ],
    'Street.Category3.Bridge.Color': '#6E787D3C',
    'Street.Category3.Arrow.Color': [
      'interpolate',
      ['linear'],
      ['zoom'],
      17,
      '#B0B5BA00',
      17.25,
      '#B0B5BA',
      20,
      '#B0B5BA',
      24,
      '#BCC1C5',
    ],
    'Street.Category4.Bridge.Color': '#6E787D3C',
    'Street.Category4.Arrow.Color': '#DADCE0',
    'Street.Walkway.Bridge.Color': '#8A92983C',
    'Street.Category4.Label.Ramp.Size': 0,
    'Street.Pedestrian.Label.Unpaved.Color': '#000000',
    'Street.Pedestrian.Label.Unpaved.Outline.Color': '#E8EAED96',
    'ExtrudedBuilding.Color': '#F1F3F4',
    'CongestionZone.Color': [
      'interpolate',
      ['linear'],
      ['zoom'],
      0,
      '#32373933',
      9,
      '#32373926',
      10,
      '#32373926',
      11,
      '#32373921',
      12,
      '#3237391A',
      13,
      '#3237390D',
      20,
      '#32373903',
    ],
    'Street.Category0.Color': '#F9E39D',
    'Street.Category0.Tunnel.Color': '#F9E39D',
    'Street.Category0.Width': [
      'interpolate',
      ['linear'],
      ['zoom'],
      0,
      6,
      5,
      6,
      6,
      6,
      7,
      6,
      8,
      6,
      9,
      6,
      10,
      6.9,
      11,
      5,
      12,
      5,
      13,
      5,
      14,
      5,
      15,
      5,
      16,
      5,
      17,
      10,
      18,
      10,
      19,
      10,
      20,
      2,
      24,
      2,
    ],
    'Street.Category1.Color': '#EEAE3C',
    'Street.Category1.Tunnel.Color': '#EEAE3C',
    'Street.Category2.Color': '#FFFFFF',
    'Street.Category2.Tunnel.Color': '#FFFFFF',
    'Street.Category3.Color': '#FFFFFF',
    'Street.Category3.Tunnel.Color': '#FFFFFF',
    'Street.Category4.Color': '#FFFFFF',
    'Street.Category4.Outline.Width': 1.1,
    'Street.Category4.Tunnel.Color': '#FFFFFF',
    'Street.Walkway.Color': '#E8EAED',
    'Street.Walkway.Tunnel.Color': '#E8EAED',
    'Street.Pedestrian.Color': '#E8EAED',
    'Chairlift.Line.Color': ['interpolate', ['linear'], ['zoom'], 13, '#8E969B', 15, '#3B4043'],
    'Chairlift.Label.Color': '#43494C',
    'Chairlift.Label.Outline.Color': '#E8EAED',
    'SkiRun.Line.Color': '#E8EAED',
    'SkiRun.Outline.Color': '#9AA1A6',
    'SkiRun.Label.Color': '#6D777C',
    'SkiRun.Label.Outline.Color': [
      'interpolate',
      ['linear'],
      ['zoom'],
      11,
      '#E8EAEDF2',
      12,
      '#E8EAEDF2',
      14,
      '#E8EAEDD9',
      17,
      '#E8EAEDCC',
    ],
    'ParkingArea.Color': ['interpolate', ['linear'], ['zoom'], 15, '#D8DBDE', 16, '#D8DBDE'],
    'POI.Accomodation.Label.Outline.Color': '#E8EAEDBF',
    'POI.Automotive.Label.Outline.Color': '#FFFFFF',
    'POI.BusinessServicesAreas.Label.Outline.Color': '#FFFFFFBF',
    'POI.EatDrink.Label.Outline.Color': '#FFFFFF',
    'POI.Emergency.Label.Outline.Color': '#FFFFFF',
    'POI.Entertainment.Label.Outline.Color': '#E8EAEDBF',
    'POI.Facilities.Label.Outline.Color': '#FFFFFF',
    'POI.LeisureOutdoor.Label.Outline.Color': '#E8EAEDBF',
    'POI.Shopping.Label.Outline.Color': '#E8EAEDBF',
    'POI.SightsMuseum.Label.Outline.Color': '#FFFFFF',
    'POI.TransitStop.Label.Outline.Color': '#E8EAEDBF',
    'Rail.Outline.Color': '#C0C5C9',
    'Street.Category0.Tunnel.Outline.Color': '#D69131',
    'Street.Category1.Tunnel.Outline.Color': '#EEB441',
    'Street.Category2.Tunnel.Outline.Color': '#B8B6B6',
    'Street.Category3.Tunnel.Outline.Color': '#B8B6B6',
    'Street.Category4.Tunnel.Outline.Color': '#B8B6B6',
    'Street.Walkway.Bridge.Baseline.Color': [
      'interpolate',
      ['linear'],
      ['zoom'],
      5,
      '#DEE0E4',
      12,
      '#DFE1E4',
      15,
      '#DFE1E4',
      16,
      '#DDDFE3',
    ],
    'Street.Pedestrian.Bridge.Baseline.Color': [
      'interpolate',
      ['linear'],
      ['zoom'],
      5,
      '#DEE0E4',
      12,
      '#DFE1E4',
      15,
      '#DFE1E4',
      16,
      '#DDDFE3',
    ],
    'Ocean.Label.Outline.Color': '#DDDFE34B',
    'Sea.Label.Outline.Color': '#DDDFE34B',
    'Fjord.Label.Color': '#5F676C',
    'Fjord.Label.Outline.Color': '#DDDFE34B',
    'Strait.Label.Color': '#5F676C',
    'Strait.Label.Outline.Color': '#DDDFE34B',
    'Sea.Label.Color': '#5F676C',
    'Ocean.Label.Color': '#5F676C',
    'BayHarbor.Label.Color': '#5F676C',
    'BayHarbor.Label.Outline.Color': '#DDDFE34B',
    'River.Color': '#5283ED',
    'CanalWaterChannel.Color': '#5283ED',
    'IntermittentRiver.Color': '#5283ED',
    'Street.Pedestrian.Tunnel.Color': '#E8EAED',
    'Street.Pedestrian.Bridge.Color': '#8A92983C',
  },
}
